
# ==========================================
# AFL PNG Seed Patcher (8-byte Zero Header)
# ==========================================

# Generated by Gemini and checked by human

INPUT_DIR="./seeds"
OUTPUT_DIR="./seeds_with_config"


if [ ! -d "$INPUT_DIR" ]; then
    echo "[-] Failed to find '$INPUT_DIR'."
    exit 1
fi

mkdir -p "$OUTPUT_DIR"
echo "[*] Start processing... Output dir: $OUTPUT_DIR"

count=0

for img in "$INPUT_DIR"/*.png; do
    [ -e "$img" ] || continue 
    
    filename=$(basename "$img")
    
    printf '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' | cat - "$img" > "$OUTPUT_DIR/$filename"
    
    ((count++))
done

echo "[+] Finished adding 16-byte header for $count seeds."