# I'm using the non-desktop docker
docker context use default
docker info

mkdir -p crash/default/crashes/
docker build -t my-fuzzer .

docker run -it --name fuzz my-fuzzer:latest
make

make fuzz

afl-tmin -i ./triaged_crashes/heap-buffer-overflow/id\:000060\,sig\:06\,src\:000022\,time\:91828\,execs\:80136\,op\:havoc\,rep\:14 -o ./minimized_crash.png -- ./png_fuzz @@


# Categorize crashes
# warn: generated by gemini
TARGET_BIN="./png_fuzz"
CRASH_DIR="findings/default/crashes"
TRIAGE_DIR="triaged_crashes"

mkdir -p "$TRIAGE_DIR"

echo "Categorizing crash files by bug type..."
for crash_file in "$CRASH_DIR"/id*; do
    [ -f "$crash_file" ] || continue
    filename=$(basename "$crash_file")
    bug_type=$(timeout 2 "$TARGET_BIN" "$crash_file" 2>&1 | grep "ERROR: AddressSanitizer:" | head -n 1 | awk '{print $3}')
    if [ -z "$bug_type" ]; then
        bug_type="other_crashes"
    fi
    mkdir -p "$TRIAGE_DIR/$bug_type"
    cp "$crash_file" "$TRIAGE_DIR/$bug_type/"
    echo "[-] categorize: $filename -> $bug_type"
done
echo "Finished! See $TRIAGE_DIR"


# Counting different crashes
# warn: generated by gemini
for f in findings/default/crashes/id*; do 
    out=$(timeout 2 ./png_fuzz "$f" 2>&1)
    type=$(echo "$out" | grep "ERROR: AddressSanitizer:" | awk '{print $3}')
    frame=$(echo "$out" | grep -m 1 -oP '(?<=#1 0x[0-9a-f]{12} in ).*?(?= )')
    if [ -n "$type" ]; then echo "$type @ $frame"; fi
done | sort | uniq -c | sort -nr
