#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <png.h>

#define MAX_DIM 256
#define CONFIG_SIZE 16 // the number of leading bytes used for configuration instead of png


// Callback function to fuzz png_set_read_user_transform_fn(...)
void my_fuzz_transform_callback(png_structp png_ptr, png_row_infop row_info, png_bytep data) {
    // warn: generated by Gemini
    if (data == NULL || row_info->rowbytes == 0) return;

    uint8_t *user_config = (uint8_t *)png_get_user_transform_ptr(png_ptr);
    if (!user_config) return;

    // use byte 13 of our configuration bytes
    uint8_t op = user_config[13] % 3; 

    switch (op) {
        case 0:
            data[0] ^= 0xFF; 
            break;
        case 1:
            data[row_info->rowbytes - 1] = 0; 
            break;
        case 2:
            break;
    }
}


void run_png_set(png_struct *png, uint8_t config[CONFIG_SIZE]){
    // Call various png_set_*. We don't call all of them together because some are contraditory (and libpng will ignore the second one), also a fixed plan may hide some bug (cumulative effect). Therefore, we use "random" bytes generated by AFL to set up the png_set_*. 

    uint32_t flags = *(uint32_t*)&config[0];
    if (flags & (1 << 0)) png_set_strip_16(png);
    if (flags & (1 << 1)) png_set_strip_alpha(png);
    // if (flags & (1 << 2)){
    //     int num_palette = 256; 
    //     int max_colors = config[4]; // 0-255
    //     int full_dither = config[5] % 2; // 0 or 1

    //     png_color palette[256];
    //     png_uint_16 histogram[256];

    //     memset(palette, 0, sizeof(palette));
    //     memset(histogram, 0, sizeof(histogram));

    //     png_set_dither(png, palette, 256, max_colors, histogram, full_dither);
    // }
    if (flags & (1 << 3)){
        // warn: generated by Gemini
        uint16_t raw_scrn, raw_file;
        memcpy(&raw_scrn, &config[6], 2);
        memcpy(&raw_file, &config[8], 2);
        // map 0~65535 to 0.1~10.0
        double scrn_gamma = 0.1 + ((double)raw_scrn / 65535.0) * 9.9;
        double file_gamma = 0.1 + ((double)raw_file / 65535.0) * 9.9;
        png_set_gamma(png, scrn_gamma, file_gamma);
    }
    if (flags & (1 << 4)) png_set_expand(png);
    if (flags & (1 << 5)) png_set_palette_to_rgb(png);
    if (flags & (1 << 6)) png_set_expand_gray_1_2_4_to_8(png);
    if (flags & (1 << 7)) png_set_gray_1_2_4_to_8(png);
    if (flags & (1 << 8)) png_set_tRNS_to_alpha(png);
    if (flags & (1 << 9)) png_set_gray_to_rgb(png);
    if (flags & (1 << 10)){
        // warn: generated by Gemini
        uint8_t raw_err = config[10];
        uint8_t raw_red = config[11];
        uint8_t raw_green = config[12];
        int error_action = (raw_err % 3) + 1;
        if (raw_red < 25) {
            png_set_rgb_to_gray(png, error_action, -1.0, -1.0);
        } else if (raw_red < 50) {
            png_set_rgb_to_gray_fixed(png, error_action, -1, -1);
        } else {
            // map to 0.0 ~ 1.0
            double red_f = (double)raw_red / 255.0;
            double green_f = (double)raw_green / 255.0;
            
            if (flags & (1 << 11)) {
                png_set_rgb_to_gray(png, error_action, red_f, green_f);
            } else {
                png_fixed_point red_fixed = (png_fixed_point)(red_f * 100000.0);
                png_fixed_point green_fixed = (png_fixed_point)(green_f * 100000.0);
                png_set_rgb_to_gray_fixed(png, error_action, red_fixed, green_fixed);
            }
        }
    }
    if (flags & (1 << 11)){
        png_set_read_user_transform_fn(png, my_fuzz_transform_callback);
        png_set_user_transform_info(png, config, 8, 3); // The two numbers are arbitrary (but valid).
    }
}


int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <png_file>\n", argv[0]);
        return 1;
    }

    FILE *fp = fopen(argv[1], "rb");
    if (!fp)
        return 1;

    /*Read config from file*/
    uint8_t config[CONFIG_SIZE];
    if (fread(config, 1, CONFIG_SIZE, fp) != CONFIG_SIZE) {
        fclose(fp);
        return 0;
    }

    png_structp png = png_create_read_struct(
        PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
    if (!png) {
        fclose(fp);
        return 1;
    }

    png_infop info = png_create_info_struct(png);
    if (!info) {
        png_destroy_read_struct(&png, NULL, NULL);
        fclose(fp);
        return 1;
    }


    if (setjmp(png_jmpbuf(png))) {
        png_destroy_read_struct(&png, &info, NULL);
        fclose(fp);
        return 0;
    }

    png_init_io(png, fp);
    png_read_info(png, info);


    png_uint_32 width = png_get_image_width(png, info);
    png_uint_32 height = png_get_image_height(png, info);

    if (width == 0 || height == 0 || width > MAX_DIM || height > MAX_DIM) {
        png_destroy_read_struct(&png, &info, NULL);
        fclose(fp);
        return 0;
    }
    // Transformations to standardize the image format for fuzzing:
    run_png_set(png, config);


    png_set_interlace_handling(png);
    png_read_update_info(png, info);

    png_size_t rowbytes = png_get_rowbytes(png, info);
    if (rowbytes == 0) {
        png_destroy_read_struct(&png, &info, NULL);
        fclose(fp);
        return 0;
    }


    png_bytep *row_pointers = malloc(height * sizeof(png_bytep));
    if (!row_pointers) {
        png_destroy_read_struct(&png, &info, NULL);
        fclose(fp);
        return 0;
    }

    for (png_uint_32 y = 0; y < height; y++) {
        row_pointers[y] = malloc(rowbytes);
        if (!row_pointers[y]) {
            for (png_uint_32 j = 0; j < y; j++)
                free(row_pointers[j]);
            free(row_pointers);
            png_destroy_read_struct(&png, &info, NULL);
            fclose(fp);
            return 0;
        }
    }

    for (png_uint_32 y = 0; y < height; y++)
        png_read_row(png, row_pointers[y], NULL);

    png_read_end(png, NULL);

    for (png_uint_32 y = 0; y < height; y++)
        free(row_pointers[y]);
    free(row_pointers);
    png_destroy_read_struct(&png, &info, NULL);
    fclose(fp);

    return 0;
}