/*
    Source:
    - AFL setup (e.g. __AFL_FUZZ_INIT): exercise-fuzzing.pdf
    - How to read png: https://www.libpng.org/pub/png/libpng-manual.txt


    Setup:
    We are using the first CONFIG_SIZE for configuration. Therefore, we must insert CONFIG_SIZE bytes to the beginning of each input PNG file. convert_seeds.sh can be used to set up the seeds.

    Don't forget to disable CRC check in the library!
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <png.h>
#include <assert.h>

// Uncomment this line to support reading from file during the debug phase
// #define DEBUG_FILE_INPUT

#define HERE fprintf(stderr, "%s: %d\n", __FILE__, __LINE__);
#define PNG_LIB_STR PNG_LIBPNG_VER_STRING
#define CONFIG_SIZE 32 // the number of leading bytes used for configuration instead of png

// We limit width x height so that we have better flexibililty
#define PNG_MAX_PIXELS 262144
#define PNG_MAX_WIDTH 4096
#define PNG_MAX_HEIGHT 4096

// Custom png read handler.
struct png_read_handle {
    const png_byte* data;
    const png_size_t size;
    png_size_t offset;
};

// The callback function provided to png_set_read_fn(). Copies data from afl buffer to *data. Updates the read handler.
void png_read_callback_fn(png_struct *png, png_byte *out_data, png_size_t length){
    struct png_read_handle* handle = (struct png_read_handle*)png_get_io_ptr(png);
    if (handle->offset + length > handle->size) png_error(png, "read past end of input");
    memcpy(out_data, handle->data + handle->offset, length);
    handle->offset += length;
    // fprintf(stderr, "Callback got data, first byte: %02X\n", out_data[0]);
}

// Support debugging with a file input (instead of AFL buffer in memory)
void load_file_to_buf(char* filename, unsigned char **buf, int* len){
    FILE *fp = fopen(filename, "rb");
    assert(fp);

    fseek(fp, 0, SEEK_END);
    long file_size = ftell(fp);
    fseek(fp, 0, SEEK_SET);

    *buf = (unsigned char *)malloc(file_size);
    assert(buf);
    
    size_t read_bytes = fread(*buf, 1, file_size, fp);
    assert(read_bytes == file_size);

    *len = read_bytes;

    fclose(fp);
    printf("load finished, read %d bytes\n", *len);
    
    return;
}

// debug output
void print_image_bytes(png_bytep* row_pointers, png_uint_32 height, png_uint_32 rowbytes){
    for (png_uint_32 i = 0; i < height; i++) {
        if (row_pointers[i] != NULL) {
            for (size_t j = 0; j < rowbytes; j++) {
                printf("%02X ", row_pointers[i][j]); 
            }
        }
        printf("\n");
    }
}

// Callback function to fuzz png_set_read_user_transform_fn(...)
void my_fuzz_transform_callback(png_structp png_ptr, png_row_infop row_info, png_bytep data) {
    // warn: generated by Gemini
    if (data == NULL || row_info->rowbytes == 0) return;

    uint8_t *user_config = (uint8_t *)png_get_user_transform_ptr(png_ptr);
    if (!user_config) return;

    // use byte 13 of our configuration bytes
    uint8_t op = user_config[13] % 3; 

    switch (op) {
        case 0:
            data[0] ^= 0xFF; 
            break;
        case 1:
            data[row_info->rowbytes - 1] = 0; 
            break;
        case 2:
            break;
    }
}

// Read the first 4 bytes from the input. The bitmask is used for png_set_* configuration.
void read_configuration_bytes(unsigned char *buf, uint8_t out[CONFIG_SIZE]){
    memcpy(out, buf, CONFIG_SIZE);
}

void run_png_set(png_struct *png, png_infop info, uint8_t config[CONFIG_SIZE]){
    // Call various png_set_*. We don't call all of them together because some are contraditory (and libpng will ignore the second one), also a fixed plan may hide some bug (cumulative effect). Therefore, we use "random" bytes generated by AFL to set up the png_set_*. 

    uint32_t flags = *(uint32_t*)&config[0];
    if (flags & (1 << 0)) png_set_strip_16(png);
    if (flags & (1 << 1)) png_set_strip_alpha(png);
    if (flags & (1 << 2)){
        int num_palette = 256; 
        int max_colors = config[4]; // 0-255
        int full_dither = config[5] % 2; // 0 or 1

        png_color palette[256];
        png_uint_16 histogram[256];

        memset(palette, 0, sizeof(palette));
        memset(histogram, 0, sizeof(histogram));

        png_set_dither(png, palette, 256, max_colors, histogram, full_dither);
    }
    if (flags & (1 << 3)){
        // warn: generated by Gemini
        uint16_t raw_scrn, raw_file;
        memcpy(&raw_scrn, &config[6], 2);
        memcpy(&raw_file, &config[8], 2);
        // map 0~65535 to 0.1~10.0
        double scrn_gamma = 0.1 + ((double)raw_scrn / 65535.0) * 9.9;
        double file_gamma = 0.1 + ((double)raw_file / 65535.0) * 9.9;
        png_set_gamma(png, scrn_gamma, file_gamma);
    }
    if (flags & (1 << 4)) png_set_expand(png);
    if (flags & (1 << 5)) png_set_palette_to_rgb(png);
    if (flags & (1 << 6)) png_set_expand_gray_1_2_4_to_8(png);
    if (flags & (1 << 7)) png_set_gray_1_2_4_to_8(png);
    if (flags & (1 << 8)) png_set_tRNS_to_alpha(png);
    if (flags & (1 << 9)) png_set_gray_to_rgb(png);
    if (flags & (1 << 10)){
        // warn: generated by Gemini
        uint8_t raw_err = config[10];
        uint8_t raw_red = config[11];
        uint8_t raw_green = config[12];
        int error_action = (raw_err % 3) + 1;
        if (raw_red < 25) {
            png_set_rgb_to_gray(png, error_action, -1.0, -1.0);
        } else if (raw_red < 50) {
            png_set_rgb_to_gray_fixed(png, error_action, -1, -1);
        } else {
            // map to 0.0 ~ 1.0
            double red_f = (double)raw_red / 255.0;
            double green_f = (double)raw_green / 255.0;
            
            if (flags & (1 << 11)) {
                png_set_rgb_to_gray(png, error_action, red_f, green_f);
            } else {
                png_fixed_point red_fixed = (png_fixed_point)(red_f * 100000.0);
                png_fixed_point green_fixed = (png_fixed_point)(green_f * 100000.0);
                png_set_rgb_to_gray_fixed(png, error_action, red_fixed, green_fixed);
            }
        }
    }
    if (flags & (1 << 11)){
        png_set_read_user_transform_fn(png, my_fuzz_transform_callback);
        png_set_user_transform_info(png, config, 8, 3); // The two numbers are arbitrary (but valid).
    }
    if (flags & (1 << 12)){
        png_color_16 bg_color;
         png_colorp palette;
        int num_palette = 0;
        if (png_get_PLTE(png, info, &palette, &num_palette) && num_palette > 0) {
            bg_color.index = config[14] % num_palette;
        } else {
            bg_color.index = 0;
        }
        bg_color.red   = (config[15] << 8) | config[16];
        bg_color.green = (config[17] << 8) | config[18];
        bg_color.blue  = (config[19] << 8) | config[20];
        bg_color.gray  = (config[21] << 8) | config[22];
        int gamma_code = config[23] % 4;
        int need_expand = config[24] % 2;
        double bg_gamma = (double)(config[25] + 1) / 100.0;
        png_set_background(png, &bg_color, gamma_code, need_expand, bg_gamma);
    }

}

#ifndef DEBUG_FILE_INPUT
__AFL_FUZZ_INIT(); 
#endif
int main(int argc, char **argv) {

    setvbuf(stdout, NULL, _IONBF, 0);

#ifdef DEBUG_FILE_INPUT
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <png_file>\n", argv[0]);
        return 1;
    }
    unsigned char *buf;
    int len;
    load_file_to_buf(argv[1], &buf, &len);
#else
    __AFL_INIT(); /* deferred fork server */
    unsigned char *buf = __AFL_FUZZ_TESTCASE_BUF;
#endif
#ifndef DEBUG_FILE_INPUT
    while (__AFL_LOOP(10000)) {

        int len = __AFL_FUZZ_TESTCASE_LEN;
#endif
        png_uint_32 height = 0; // accessed in cleanup
        png_uint_32 width = 0; 
        png_bytep* volatile row_pointers = NULL; // accessed in cleanup
        png_bytep volatile image_data = NULL;
        png_struct* png = NULL;
        png_info* info = NULL;
        uint8_t config[CONFIG_SIZE];

        if (len <= CONFIG_SIZE) continue;
        read_configuration_bytes(buf, config);

        /* Initialize struct */ 
        png = png_create_read_struct(PNG_LIB_STR, NULL, NULL, NULL);
        if (!png) continue;
        info = png_create_info_struct(png);
        if (!info) goto cleanup;

        if (setjmp(png_jmpbuf(png))){
            // Handle all libpng longjmp
            goto cleanup;
        }

        /* set up input source */
        // We need to read from buf (i.e. __AFL_FUZZ_TESTCASE_BUF).
        // io_ptr:
        // read_data_fn: libpng calls this function when it reads png data. Copy the data from our testcase buf to libpng buffer.
        struct png_read_handle read_handle = {
            .data = buf + CONFIG_SIZE,
            .size = (png_size_t)len - CONFIG_SIZE,
            .offset = 0
        };
        png_set_read_fn(png, &read_handle, png_read_callback_fn);

        
        /* read header and metadata chunks */
        png_read_info(png, info);

        /* resource limit */
        width = png_get_image_width(png, info);
        height = png_get_image_height(png, info);

        if ((width == 0) || (height == 0) || (width > PNG_MAX_WIDTH) || (height > PNG_MAX_HEIGHT) || (width * height > PNG_MAX_PIXELS)){
            goto cleanup;
        }

        /* optionally apply transformations */
        
        run_png_set(png, info, config);
        png_read_update_info(png, info);

        /* read pixel data */
        // WARN: Call png_read_update_info(png, info) before png_get_rowbytes if any transformation is performed
        size_t rowbytes = png_get_rowbytes(png, info);
        size_t max_safe_rowbytes = width * 8;
        rowbytes = (rowbytes > max_safe_rowbytes) ? rowbytes : max_safe_rowbytes;
        row_pointers = (png_bytep *)png_malloc(png, height * sizeof(png_bytep));
        if (((size_t)height) > (PNG_SIZE_MAX / rowbytes)) {
            png_free(png, row_pointers);
            png_error(png, "image_data buffer too large");
        }
        image_data = (png_bytep)png_malloc(png, height * rowbytes);
        for (png_uint_32 i = 0; i < height; i++) {
            row_pointers[i] = image_data + i * rowbytes;
        }

        png_read_image(png, row_pointers); // read the png into row_pointers
        png_read_end(png, NULL);
        // print_image_bytes(row_pointers, height, rowbytes);
        
    cleanup:
        if (image_data) {
            png_free(png, image_data);
        }
        if (row_pointers){
            png_free(png, row_pointers);
        }
        
        png_destroy_read_struct(&png, &info, NULL);
#ifdef DEBUG_FILE_INPUT
        free(buf);
#endif

#ifndef DEBUG_FILE_INPUT
    }
#endif
    return 0;
}